### ISSUE TITLE
clerkbot 3 will not load channels from imported database

### ISSUE THREAD

**Issue by AntiCompositeNumber** [countervandalism/cvn-clerkbot#10]
Fails with
```
2023-01-14 21:16:30+0000 [CVNClerkBot,client] Unhandled Error
	Traceback (most recent call last):
	  File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 249, in _dataReceived
	    rval = self.protocol.dataReceived(data)
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 2631, in dataReceived
	    basic.LineReceiver.dataReceived(self, data)
	  File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 572, in dataReceived
	    why = self.lineReceived(line)
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 2644, in lineReceived
	    self.handleCommand(command, prefix, params)
	--- <exception caught here> ---
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 2699, in handleCommand
	    method(prefix, params)
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 1963, in irc_RPL_WELCOME
	    self.signedOn()
	  File "/srv/cvn/git/CVNClerkBot/cvnclerkbot.py", line 57, in signedOn
	    self.join(channel[0])
	  File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 1545, in join
	    if channel[0] not in CHANNEL_PREFIXES:
	builtins.TypeError: 'in <string>' requires string as left operand, not int
```

Tried to run it with pdb, but the post-mortem debugger didn't pick it up.

**Comment by AntiCompositeNumber** [comment]
Fixed in 2f939fe7d25db8d1455bab5267a4f4d253d9dfeb
