### ISSUE TITLE
cvn-clerkbot 3 unstable due to UnicodeDecodeError

### ISSUE THREAD

**Issue by AntiCompositeNumber** [countervandalism/cvn-clerkbot#11]
Repeated disconnects with
```
2023-01-14 22:55:04+0000 [-] Starting factory <__main__.CVNClerkBotFactory object at 0x7fbcb51aea00>
2023-01-14 23:13:06+0000 [CVNClerkBot,client] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 103, in callWithLogger
            return callWithContext({"system": lp}, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/log.py", line 86, in callWithContext
            return context.call({ILogContext: newCtx}, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 122, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python3/dist-packages/twisted/python/context.py", line 85, in callWithContext
            return func(*args,**kw)
        --- <exception caught here> ---
          File "/usr/lib/python3/dist-packages/twisted/internet/posixbase.py", line 614, in _doReadOrWrite
            why = selectable.doRead()
          File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 243, in doRead
            return self._dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/internet/tcp.py", line 249, in _dataReceived
            rval = self.protocol.dataReceived(data)
          File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 2631, in dataReceived
            basic.LineReceiver.dataReceived(self, data)
          File "/usr/lib/python3/dist-packages/twisted/protocols/basic.py", line 572, in dataReceived
            why = self.lineReceived(line)
          File "/usr/lib/python3/dist-packages/twisted/words/protocols/irc.py", line 2637, in lineReceived
            line = line.decode("utf-8")
        builtins.UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 498: unexpected end of data
        
2023-01-14 23:13:06+0000 [CVNClerkBot,client] <twisted.internet.tcp.Connector instance at 0x7fbcb51ae9d0 disconnected IPv4Address(type='TCP', host='irc.libera.chat', port=6667)> will retry in 258 seconds
2023-01-14 23:13:06+0000 [-] Stopping factory <__main__.CVNClerkBotFactory object at 0x7fbcb51aea00>
```

I'm guessing that one of the bots is truncating something weird, causing a Unicode error. Not sure what channel or message yet.

**Comment by AntiCompositeNumber** [comment]
```
2023-01-15 15:40:35+0000 [CVNClerkBot,client] b':CVNBot26!~CVNBot26@cvn/bot/CVNBots-F PRIVMSG #cvn-ar-scan :\x0313User\x0314 [[ar:User:Attaremad]] \x0313uploaded\x0314 [[ar:Image:Croupier FILMAFFINITY.jpg]] \x0310URL:\x0312 https://ar.wikipedia.org/wiki/Image%3aCroupier_FILMAFFINITY.jpg\x0314 "{{\xd9\x85\xd8\xb9\xd9\x84\xd9\x88\xd9\x85\xd8\xa7\xd8\xaa | \xd9\x88\xd8\xb5\xd9\x81  = \xd9\x87\xd8\xb0\xd8\xa7 \xd9\x85\xd9\x84\xd8\xb5\xd9\x82:\xd8\xa8\xd9\x88\xd8\xb3\xd8\xaa\xd8\xb1 \xd8\xa7\xd9\x84\xd9\x81\xd9\x8a\xd9\x84\xd9\x85 \xd8\xa7\xd9\x84\xd8\xa8\xd8\xb1\xd9\x8a\xd8\xb7\xd8\xa7\xd9\x86\xd9\x8a (\xd9\x85\xd8\xaf\xd9\x8a\xd8\xb1 \xd9\x85\xd8\xa7\xd8\xa6\xd8\xaf\xd8\xa9 \xd8\xa7\xd9\x84\xd9\x82\xd9\x85\xd8\xa7\xd8\xb1) 1998   | \xd9\x85\xd8\xb5\xd8\xaf\xd8\xb1 = (https://pics.filmaffinity.com/croupier-306990370-large.jpg) | \xd8\xaa\xd8\xa7\xd8\xb1\xd9\x8a\xd8\xae=15-01-2023  | \xd9\x85\xd9\x86\xd8\xaa\xd8\xac =filmaffinity.com | \xd8\xa5\xd8\xb0\xd9\x86  = \xd8\xa7\xd9\x86\xd8\xb8\xd8\xb1 \xd8\xa3\xd8\xaf\xd9'
```
